var svc = {};

svc.getFamilies = function(req, res) {
    res.json(['Strings', 'Woodwinds', 'Brass']);
};

svc.getInstruments = function(req, res) {
    var instruments = [
        {
            name: 'Alto Flute',
            family: 'Woodwinds',
            imgUrl: '',
            rangeBottom: 'C4',
            rangeTop: 'C7',
            key: 'G',
        },
        {
            name: 'Bass Clarinet',
            family: 'Woodwinds',
            imgUrl: '',
            rangeBottom: 'E3',
            rangeTop: 'E6',
            key: 'Bb',
        },
        {
            name: 'Bass Flute',
            family: 'Woodwinds',
            imgUrl: '',
            rangeBottom: 'C4',
            rangeTop: 'C7',
            key: 'C',
        },
        {
            name: 'Bassoon',
            family: 'Woodwinds',
            imgUrl: '',
            rangeBottom: 'Bb1',
            rangeTop: 'E5',
            key: 'C',
        },
        {
            name: 'Clarinet',
            family: 'Woodwinds',
            imgUrl: '',
            rangeBottom: 'E3',
            rangeTop: 'C6',
            key: 'Bb',
        },
        {
            name: 'Contrabass Clarinet',
            family: 'Woodwinds',
            imgUrl: '',
            rangeBottom: 'C3',
            rangeTop: 'E6',
            key: 'Bb',
        },
        {
            name: 'Contrabassoon',
            family: 'Woodwinds',
            imgUrl: '',
            rangeBottom: 'Bb1',
            rangeTop: 'A4',
            key: '',
        },
        {
            name: 'Eb Clarinet',
            family: 'Woodwinds',
            imgUrl: '',
            rangeBottom: 'E3',
            rangeTop: 'C7',
            key: 'Eb',
        },
        {
            name: 'English Horn',
            family: 'Woodwinds',
            imgUrl: '',
            rangeBottom: 'B3',
            rangeTop: 'E6',
            key: 'F',
        },
        {
            name: 'Flute',
            family: 'Woodwinds',
            imgUrl: '',
            rangeBottom: 'C4',
            rangeTop: 'C7',
            key: 'C',
        },
        {
            name: 'Oboe',
            family: 'Woodwinds',
            imgUrl: '',
            rangeBottom: 'Bb3',
            rangeTop: 'G6',
            key: 'C',
        },
        {
            name: 'Piccolo',
            family: 'Woodwinds',
            imgUrl: '',
            rangeBottom: 'D4',
            rangeTop: 'C7',
            key: 'C',
        },
        {
            name: 'Soprano Sax',
            family: 'Woodwinds',
            imgUrl: '',
            rangeBottom: 'Bb3',
            rangeTop: 'F6',
            key: 'Bb',
        },
        {
            name: 'Alto Sax',
            family: 'Woodwinds',
            imgUrl: '',
            rangeBottom: 'Bb3',
            rangeTop: 'F6',
            key: 'Eb',
        },
        {
            name: 'Tenor Sax',
            family: 'Woodwinds',
            imgUrl: '',
            rangeBottom: 'Bb3',
            rangeTop: 'F6',
            key: 'Bb',
        },
        {
            name: 'Baritone Sax',
            family: 'Woodwinds',
            imgUrl: '',
            rangeBottom: 'Bb3',
            rangeTop: 'F6',
            key: 'Eb',
        },
        {
            name: 'Violin',
            family: 'Strings',
            imgUrl: '',
            rangeBottom: 'G3',
            rangeTop: 'B7',
            key: 'C',
        },
        {
            name: 'Viola',
            family: 'Strings',
            imgUrl: '',
            rangeBottom: 'C3',
            rangeTop: 'D7',
            key: 'C',
        },
        {
            name: 'Cello',
            family: 'Strings',
            imgUrl: '',
            rangeBottom: 'C2',
            rangeTop: 'A5',
            key: 'C',
        },
        {
            name: 'Contrabass',
            family: 'Strings',
            imgUrl: '',
            rangeBottom: 'E2',
            rangeTop: 'G4',
            key: 'C',
        },
        {
            name: 'Guitar',
            family: 'Strings',
            imgUrl: '',
            rangeBottom: 'E3',
            rangeTop: 'B6',
            key: 'C',
        },
        {
            name: 'Trumpet',
            family: 'Brass',
            imgUrl: '',
            rangeBottom: 'F#3',
            rangeTop: 'C6',
            key: 'Bb',
        },
        {
            name: 'French Horn',
            family: 'Brass',
            imgUrl: '',
            rangeBottom: 'F2',
            rangeTop: 'C6',
            key: 'F',
        },
        {
            name: 'Trombone',
            family: 'Brass',
            imgUrl: '',
            rangeBottom: 'C2',
            rangeTop: 'C5',
            key: 'C',
        },
        {
            name: 'Bass Trombone',
            family: 'Brass',
            imgUrl: '',
            rangeBottom: 'Bb0',
            rangeTop: 'C5',
            key: 'C',
        },
        {
            name: 'Tuba',
            family: 'Brass',
            imgUrl: '',
            rangeBottom: 'Eb2',
            rangeTop: 'A4',
            key: 'F/Eb/C/Bb',
        },
    ];
    const filtered = instruments.filter(function(inst) {
        return inst.family === req.query.family;
    });
    res.json(filtered);
};

module.exports = svc;